guide/index.md

fix: more smooth translation

---

guide/features.md

fix: delete duplicate translation

---

guide/ssr.md

docs: 修改错别字，润色翻译

---

guide/index.md

hash: 4ddb85649801124a2cc29e70a6da902f8328cae7
time: 2021/2/27上午4:12:49

docs: synchronize with official docs，translation

---

guide/index.md
guide/ssr.md

hash: 487b8076ce0009630049d9dd09aea17a9fe1d044
time: 2021/3/5 下午1:00:00

docs: synchronize with official docs，translation - 2021-03-05

---

config/index.md

hash: 76f35352dbfc4e16cb65005e57e2757a97675bfd
time: 2021/3/8 下午3:30:00
还有 2 个 commit [a8b4543](https://github.com/vitejs/vite/commit/a8b4543e4420bdeeeca8bc9141db30c6a9dd976e#diff-46b42b4229cd7a39c564e780bb665a8bde4fdf722007e8473f167fe53ed4b995) 和 [6720f65](https://github.com/vitejs/vite/commit/6720f65d70b11f080d56028902b8772a17414925#diff-46b42b4229cd7a39c564e780bb665a8bde4fdf722007e8473f167fe53ed4b995) 只涉及英文单词的修改，对中文文档无影响。

docs: synchronize with official docs - 2021-03-08 

---

config/index.md

hash: 5ec13d8b3fe1632f793c7ad22b21c43a13d71141
time: 2021/3/9 下午11:45:00

docs: synchronize with official docs - 2021-03-09

---

config/index.md
guide/backend-integration.md
guide/features.md

几个简单的先提一个 pr，还有一个新增页面比较长，提交在 #48  中。

docs: synchronize with official docs，translation - 2021-03-16 v1

---

guide/index.md

hash: 613ca0e6993b397f4dd9e1e02be1670c04c255a9
time: 2021/3/17 下午1:15:00

docs: synchronize with official docs - 2021-03-17

---

config/index.md
guide/comparisons.md
guide/env-and-mode.md

update: sychronized with official docs.

---

guide/features.md

chore: update css-pre-processors

---

.vitepress/config.js

Link: #54 Linking from main docs and keeping URLs consistent across translations

chore: add lang nav link in config.js

---

guide/ssr.md
guide/static-deploy.md
guide/using-plugins.md
guide/why.md

docs: add some anchor points and proofreading

---

guide/features.md

docs(guide/features.md):  review features.md, translation enhancement

---

guide/comparisons.md

[specify a term translation convention](https://github.com/vitejs/docs-cn/issues/163)

review: guide/comparisons

---

.vitepress/theme/custom.css
.vitepress/theme/fetchReleaseTag.js
index.md

chore: add release tag tip for index.md

---

guide/features.md

Fix a small translation glitch in the doc.

Update translation for features section

---

.vitepress/rewrite-title/index.js
package.json
scripts/build.js

为了未来中文文档更多可能的需求，特此新在 scripts 文件夹中建立了 build.js 脚本文件用于构建。

chore: new build script

---

guide/index.md

improve translation to solve #190

fix: improve translation to solve #190

---

guide/assets.md

https://github.com/vitejs/docs-cn/commit/fc91e5425f0f261aa7e44d5748b4afbafb6d33c0

docs(cn): warning for new URL(url, import.meta.url) (#7279)

---

config/index.md

docs(cn): remove duplicate colon

---

config/index.md

docs: translation

---

config/index.md

docs: fix TypsScript Spellings

---

.vitepress/config.ts

chore: update editLink

---

plugins/index.md

统一为句末添加了句号，不然看着有点难受
还去掉了一个 `>`，因为英文文档并没有出现

docs: fix period at the end of a sentence

---

guide/features.md

docs: minor fixes to details of Web Workers

---

guide/dep-pre-bundling.md

chore: fix syntax

---

config/index.md

docs: fix formats for config/index page

---

config/build-options.md
guide/api-hmr.md
guide/build.md

docs: add translation 

---

guide/build.md

fix typo: '#rebuild-on-files-changs' to '#rebuild-on-files-changes'

docs: fix typo

---

.vitepress/theme/custom.css

更新 `.docs-cn-github-release-tag`的样式，让介绍文字和版本文字对齐 `vertical-align: middle`

chore(styles): update release tag style

---

.vitepress/config.ts

fix(editLink): fix editLink pattern error

---

guide/migration.md

docs(migration): remove repeated hash

---

.vitepress/config.ts

fix: translate outlineTitle

---

LICENSE
README.md
package.json

/cc @ShenQingchuan 
closes https://github.com/vitejs/docs-cn/issues/703

chore: change license

---

.vitepress/config.ts

algolia 翻译
|before|after|
|:--:|:--:|
|![image](https://user-images.githubusercontent.com/54026110/224039692-7d6d71e7-db4a-4203-937d-352d5a659241.png)|![image](https://user-images.githubusercontent.com/54026110/224039404-46d7acc0-df5d-4433-98db-8269f464db9f.png)|

docs: algolia search translate

---

guide/api-plugin.md

docs(cn): remove duplicated translations and make them easier to understand

---

guide/index.md

docs(cn): Synchronized template presets

---

vercel.json

添加Vercel配置项 支持省略后缀名
resolve https://github.com/vitejs/docs-cn/issues/803

chore: config remove extension

---

config/server-options.md

docs: fix word errors

---

blog/announcing-vite5.md

Translate the announcing-vite5.md doc

Translate the announcing-vite5.md doc

---

guide/migration-from-v1.md

Fixed links for @ vitejs/plugin mistakes.

docs(zh): Fixed links for @ vitejs/plugin mistakes

---

guide/static-deploy.md

1. 统一风格 
2. 另外两处地方都有这个“的更改会生成”，猜测这边是漏了，阅读起来挺拗口

docs: improve descriptions

---

config/build-options.md

docs: uniform string style

---

.github/ISSUE_TEMPLATE /bug_report.yml
.github/ISSUE_TEMPLATE /config.yml

添加 issue 模版和 Vite 主仓库 issue 区指引

chore: add issue template

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml

chore: fix template not working

---

guide/ssr.md

docs(ssr): improve 'efficient invalidation' translation

---

guide/assets.md

docs(assets): fix markdown format

---

guide/why.md

Rephrased a previously awkward translation to enhance clarity and ensure the text reads naturally.

docs(cn): improve translation for better readability and natural flow

---

.vitepress/config.ts
guide/api-environment-frameworks.md
guide/cli.md
guide/index.md

Corrected some inaccurate translations

docs(cn): tweak words

---

config/shared-options.md
scripts/verifyCommit.js

docs: change case & require is not defined in ES module scope

---

guide/dep-pre-bundling.md

1. replace English colon with Chinese colon
2. fix space before and after English word

docs: fix space and colon in dep-pre-bundling.md

---

.vitepress/config.ts

chore: use minisearch

---

.vitepress/config.ts
package.json
pnpm-lock.yaml

chore: remove vitepress-plugin-llms
