vitejs/docs-cn

.vitepress/config.js

1. 修复当前中文文档 editLink 不工作的问题（英文文档是工作的）：
before：
after：
2. 调整 sidebar 的顺序以保证与英文文档一致：
before：
after（「配置参考」在最下面，与英文文档一致）：
3. 此外是一些无关紧要的格式化（vscode 按照 vite 的标准格式化的），与配置的顺序调整（尽可能与英文文档保持一致）

fix: fix editlink not working, adjust sidebar order

---

guide/index.md

精校了 index.md，请帮忙审阅。
更新了一些译文，使用了尤大在知乎翻译的 [Vite 2.0 发布了](https://zhuanlan.zhihu.com/p/351147547) 的译法：
ES Modules -> ES 模块
HMR -> 模块热更新
the rationale behind the project  -> 项目的设计初衷
legacy browers -> 旧浏览器
source code -> 源码

docs: translation enhancement, typos in index.md

---

.vitepress/config.js
scripts/verifyCommit.js
vite.config.js

在 `scripts/verifyCommit.js` 中加入了应该是遗漏了的 `style` 选项；应 wiki 的要求改变了所有的全角括号。
---
说到 semantic release，因为现在有些不规范，我写了些关于它的信息可以加入 wiki：
格式：`<type>(<scope>): <subject>`（`<scope>` 是可选的）
```
feat: add good shit
^--^  ^------------^
|     |
|     +-> Summary in present tense.
|
+-------> Type: chore, docs, feat, fix, refactor, style, or test.
```
- feat: (新功能，面向用户)
- fix: (bug 修复，面向用户)
- docs: (编辑文档)
- style: (格式，如全角半角；没有 production code 方面的改变)
- refactor: (比如重命名变量)
- test: (加入缺少的测试，没有 production code 方面的改变)
- chore: (更新依赖等，没有 production code 方面的改变)
https://www.conventionalcommits.org/

chore: omitted semantic release type (style) and changed all fullwidth brackets to halfwidth

---

.vitepress/rewrite-title/index.js
.vitepress/utils/frontmatter-service.js
index.md
package.json

由于目前文档结构中：
```
const articleDirs = ['blog', 'config', 'guide', 'plugins']
```
仅有这几个文件夹中的数篇文档内容形式以 `# xxx` 的一级标题开头，而根目录的两篇 `index.md` 和 `README.md` 都不是这样。
所以我们采取的办法是：
**在 `vitepress build` 前运行追加 title meta 的过程。**
这样构建出来的产物每一页的标题都不会是 `开始 {#getting-started} | Vite 中文文档` 的样子了。

chore: add rewrite title helper script.

---

config/index.md

这句明显和英文文档相悖。并且也不符合事实
> Assets will always be inlined, regardless of file size, and build.assetsInlineLimit will be ignored if you specify build.lib
同时也不符合代码的表现
>  in vite/src/node/plugins/asset.ts/fileToBuiltUrl line 211
``` js
let url
if (
config.build.lib || // 使用了lib模式就无视
(!file.endsWith('.svg') &&
content.length < Number(config.build.assetsInlineLimit)) // 这里是判断 assetsInlineLimit 与资源的大小
) {
// base64 inlined as a string
url = `data:${mime.getType(file)};base64,${content.toString('base64')}`
} else {
```

docs(cn): fix translation error about lib mode

---

guide/assets.md

Remove an extra `。` and refine the "import.meta.url" section to get it a bit more readable, hope so 🤔.

Refine the "import.meta.url" section

---

guide/api-plugin.md

现在线上文档https://cn.vitejs.dev/guide/api-plugin.html#conventions ，在点击「兼容的 Rollup 插件」这个锚点时无法跳转到对应的章节，英文版没有这个问题，中文版会有，修改md中的链接以使能跳转

docs(cn): fix rollup plugin compatibility anchor

---

.vitepress/theme/fetchReleaseTag.js

当`https://api.github.com/repos/vitejs/docs-cn/releases/latest`这个接口被限频时，拿不到tag_name，会导致vite前端的版本显示undefined，这里做一下兜底处理，当拿不到tag_name的时候，不显示tag_name

fix: 修正releaseTagName取不到导致前端显示undefined的问题

---

guide/migration.md

docs(cn): typo glob section for migration

---

.vitepress/markdown-it-custom-anchor/index.js

在 vitepress 的 v1.0.0-alpha.11 中删除了内置的 headings 插件，导致 md.renderer.rules.heading_open 方法不可用，所以 配置 - 构建配置页面 404 了。
关联问题 #608

fix(build): 修复 配置 -> 构建配置 页面404

---

guide/api-plugin.md

docs: add translations to api-plugin chapter

---

config/build-options.md
guide/why.md

guide/why 只是将描述 esbuild 快的措辞从 `blazing` 到了 `extremely`，所以我认为中文释义保持不变即可

docs: fix 672e43aa-1 branch conflict

---

config/build-options.md

https://github.com/vitejs/vite/blob/v4.0.4/packages/vite/src/node/build.ts#L367-L368

fix: `build.minify` force down to `es2021`

---

.vitepress/config.ts

`outlineTitle` 已经在最新的版本中[废弃](https://github.com/vuejs/vitepress/commit/8de2f4499d9364d85e6070ce4b94651a1902b101#diff-08d1bb1c444a76199b8f44b087883f932a6f8118f5ded25bf5c508fa52aa5b7f)。

feat: use new option for outline title

---

guide/ssr.md

[原文](https://vitejs.dev/guide/ssr.html#ssr-specific-plugin-logic)的描述是"The options object in load and transform is optional"，对应的中文翻译有误

fix: wrong translation

---

config/dep-optimization-options.md

对应的英文原句是 *Options to pass to esbuild during the dep scanning and optimization.* 个人感觉 `dep` 译为 `依赖` 或者 `依赖项` 更为合理

docs: correct the translation of dep

---

config/build-options.md

docs:build-options中关于soucemap描述中。
`'hidden'` 的工作原理与 `'true'` 相似
修改为
`'hidden'` 的工作原理与 `true` 相似
其中true应为boolean类型展示，现在文档为string。

docs(cn): change inaccurate value description

---

package.json

实际上应该像vite主仓库一样lock在9.5，但是目前lock文件变更会很大。主要原因是 pnpm8 和 pnpm9 文件格式变了，每行都会变更。
通过锁在8.x，使用corepack，可以避免安装依赖时起冲突
https://github.com/vitejs/vite/blob/main/package.json#L100C1-L100C34

chore(packageManager): lock in pnpm@8.9.0

---

config/server-options.md

这一块已经翻译过了，可能是处理冲突的时候 两边都保留了，可以移除英文部分

docs: remove translated English

---

plugins/index.md

English docs：https://vitejs.dev/plugins/#vitejs-plugin-react-swc
Chinese docs：https://cn.vitejs.dev/plugins/#vitejsplugin-react-swc
The anchored document position is incorrect when switching from an English document to the corresponding Chinese document

fix(plugins): fix anchor point titles

---

guide/migration.md

Fixed incorrect link in "Migrate from v4".
It should link to the migration page for v5.

docs(cn): Fix the wrong link
